import type { SettingDefinition } from "../../types/config-generator";

export const PALWORLD_CONFIGURATION_METADATA = {
  schemaVersion: 1,
  gameVersionBasis: "Palworld Server Guide 1.0.0 (reviewed 2026-07-25)",
  sourceUrl:
    "https://docs.palworldgame.com/settings-and-operation/configuration/",
  defaultBasis:
    "Standard DefaultPalWorldSettings.ini values distributed with PalServer",
} as const;

export const PALWORLD_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "ServerName",
    label: "Server Name",
    category: "General",
    description: "Name shown to players for this Palworld server.",
    type: "string",
    defaultValue: "Palworld Server",
    maximumLength: 128,
  },
  {
    key: "ServerDescription",
    label: "Server Description",
    category: "General",
    description: "Description shown for the server.",
    type: "string",
    defaultValue: "",
    maximumLength: 512,
  },
  {
    key: "ExpRate",
    label: "Experience Rate",
    category: "Gameplay",
    description: "Multiplier applied to experience gained.",
    guidance: "1.0 is the Palworld default.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "PalCaptureRate",
    label: "Pal Capture Rate",
    category: "Gameplay",
    description: "Multiplier applied to Pal capture probability.",
    guidance: "1.0 is the Palworld default.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "DeathPenalty",
    label: "Death Penalty",
    category: "Gameplay",
    description: "Controls what a player drops upon death.",
    type: "enum",
    defaultValue: "All",
    options: [
      { value: "None", label: "None — no drops" },
      { value: "Item", label: "Items except equipment" },
      { value: "ItemAndEquipment", label: "Items and equipment" },
      { value: "All", label: "Items, equipment, and team Pals" },
    ],
  },
  {
    key: "DayTimeSpeedRate",
    label: "Daytime Speed",
    category: "World",
    description: "Multiplier for daytime progression speed.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "NightTimeSpeedRate",
    label: "Nighttime Speed",
    category: "World",
    description: "Multiplier for nighttime progression speed.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "CollectionDropRate",
    label: "Gatherable Item Rate",
    category: "World",
    description: "Multiplier for items obtained from gatherable objects.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "EnemyDropItemRate",
    label: "Enemy Drop Rate",
    category: "World",
    description: "Multiplier for item quantities dropped by enemies.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "bEnableFastTravel",
    label: "Enable Fast Travel",
    category: "World",
    description: "Allows players to use fast-travel points.",
    type: "boolean",
    defaultValue: true,
  },
  {
    key: "ServerPlayerMaxNum",
    label: "Maximum Players",
    category: "Players and Guilds",
    description: "Maximum number of players who can join the server.",
    type: "number",
    defaultValue: 32,
    minimum: 1,
    step: 1,
    integer: true,
  },
  {
    key: "GuildPlayerMaxNum",
    label: "Maximum Guild Members",
    category: "Players and Guilds",
    description: "Maximum number of players allowed in a guild.",
    type: "number",
    defaultValue: 20,
    minimum: 1,
    step: 1,
    integer: true,
  },
  {
    key: "bIsPvP",
    label: "Enable PvP",
    category: "Players and Guilds",
    description: "Enables player-versus-player gameplay.",
    type: "boolean",
    defaultValue: false,
  },
  {
    key: "bShowPlayerList",
    label: "Show Player List",
    category: "Players and Guilds",
    description: "Shows the player list in the in-game menu.",
    type: "boolean",
    defaultValue: true,
  },
  {
    key: "BaseCampMaxNumInGuild",
    label: "Bases per Guild",
    category: "Bases and Pals",
    description: "Maximum number of bases that one guild may own.",
    guidance: "Pocketpair documents a default of 4 and maximum of 10.",
    warning: "Higher values increase server processing load.",
    type: "number",
    defaultValue: 4,
    minimum: 1,
    maximum: 10,
    step: 1,
    integer: true,
  },
  {
    key: "BaseCampWorkerMaxNum",
    label: "Pals per Base",
    category: "Bases and Pals",
    description: "Maximum number of working Pals at each base.",
    guidance: "Pocketpair documents a maximum of 50.",
    warning: "Higher values increase server processing load.",
    type: "number",
    defaultValue: 15,
    minimum: 1,
    maximum: 50,
    step: 1,
    integer: true,
  },
  {
    key: "PalSpawnNumRate",
    label: "Pal Spawn Rate",
    category: "Bases and Pals",
    description: "Multiplier for the number of Pals spawned.",
    warning: "Increasing this value can significantly affect performance.",
    type: "number",
    defaultValue: 1,
    minimum: 0,
    step: 0.1,
    precision: 6,
  },
  {
    key: "CrossplayPlatforms",
    label: "Crossplay Platforms",
    category: "Networking",
    description: "Platforms allowed to connect to the server.",
    guidance: "The official documented default enables all listed platforms.",
    type: "enum",
    defaultValue: "Steam,Xbox,PS5,Mac",
    serialization: "tuple",
    options: [
      { value: "Steam,Xbox,PS5,Mac", label: "Steam, Xbox, PS5, and Mac" },
      { value: "Steam", label: "Steam only" },
    ],
  },
  {
    key: "PublicPort",
    label: "Public Port",
    category: "Networking",
    description:
      "External port advertised for a community server; this does not change the listening port.",
    type: "number",
    defaultValue: 8211,
    minimum: 1,
    maximum: 65535,
    step: 1,
    integer: true,
  },
  {
    key: "RESTAPIEnabled",
    label: "Enable REST API",
    category: "Networking",
    description: "Enables the official Palworld REST API.",
    type: "boolean",
    defaultValue: false,
  },
  {
    key: "RESTAPIPort",
    label: "REST API Port",
    category: "Networking",
    description: "Listening port for the official Palworld REST API.",
    type: "number",
    defaultValue: 8212,
    minimum: 1,
    maximum: 65535,
    step: 1,
    integer: true,
  },
  {
    key: "AdminPassword",
    label: "Administrator Password",
    category: "Administration",
    description: "Password used to obtain server administrator privileges.",
    type: "string",
    defaultValue: "",
    maximumLength: 128,
    sensitive: true,
  },
  {
    key: "ServerPassword",
    label: "Server Password",
    category: "Administration",
    description: "Password players must enter to join the server.",
    type: "string",
    defaultValue: "",
    maximumLength: 128,
    sensitive: true,
  },
  {
    key: "bIsShowJoinLeftMessage",
    label: "Show Join and Leave Messages",
    category: "Administration",
    description: "Shows in-game messages when players join or leave.",
    type: "boolean",
    defaultValue: true,
  },
] as const;
